### ISSUE TITLE
[Website] Create Forum Page

### ISSUE THREAD

**Issue by evankuo1** [cptchuckles/SharpScape#3]
Website doesn't currently have a forum tab. Bret and I are going to add one.

**Comment by Bretl7** [comment]
Working on this with Evan

**Comment by cptchuckles** [comment]
Can't believe I hadn't noticed this, but #10 was actually a duplicate of this issue, and @SunnyRo already knocked it out with PR #17 - sorry guys

**Comment by cptchuckles** [comment]
#18 needs some attention if you guys want to tackle that instead

**Comment by cptchuckles** [comment]
(never mind the mention to this issue above, it's a github glitch.  make sure not to use #<number> in your commit message unless it is meant to link to a GitHub issue or PR)
